from __future__ import annotations

from collections import OrderedDict

import torch
from torch import nn

from modules.transformer_rpr import TransformerEncoder


class RPRClassifier(nn.Module):
    """Transformer encoder model for 3-class waveform classification."""

    def __init__(
        self,
        window_size: int = 50,
        channel_size: int = 150,
        stride: int = 10,
        num_heads: int = 10,
        hidden_dim: int = 2048,
        depth: int = 3,
        dropout: float = 0.1,
        num_classes: int = 3,
    ) -> None:
        super().__init__()
        self.convlayers1 = nn.Sequential(
            nn.Conv1d(3, channel_size, window_size, stride=stride),
            nn.BatchNorm1d(channel_size),
            nn.ReLU(),
        )
        self.encoder = TransformerEncoder(channel_size, num_heads, hidden_dim, depth)
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()
        self.linear = nn.Linear(channel_size, num_classes)

    def forward(self, src: torch.Tensor) -> tuple[torch.Tensor, list[torch.Tensor]]:
        x = src.permute(0, 2, 1)
        x = self.convlayers1(x)
        x = self.dropout(x)
        x = x.permute(0, 2, 1)

        cls_token = torch.randn((x.size(0), 1, x.size(2)), device=x.device)
        x = torch.cat((cls_token, x), dim=1)

        x, attn_list = self.encoder(x)
        x = self.relu(x[:, 0, :])
        x = self.dropout(x)
        logits = self.linear(x)
        return logits, attn_list


def strip_data_parallel_prefix(state_dict: dict[str, torch.Tensor]) -> OrderedDict:
    """Remove `module.` prefix generated by DataParallel checkpoints."""

    new_state_dict: OrderedDict[str, torch.Tensor] = OrderedDict()
    for key, value in state_dict.items():
        new_state_dict[key[7:] if key.startswith("module.") else key] = value
    return new_state_dict
